// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Cơ Bản',
      items: [
        'basic/pixel_structure',
        'basic/edit_project',
        'basic/connect_camera',
        'basic/first_project',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        'modules/imagesource',
        'modules/imagesource_uri',
        'modules/pattern_matching',
        'modules/shape_matching',
        'modules/measure_brightness',
        'modules/measure_color',
        'modules/count_pixel_intensity',
        'modules/count_pixel_color',
        'modules/blob_detection',
        'modules/blob_color_detection',
        'modules/find_line',
        'modules/find_circle',
        'modules/caliper',
        'modules/two_lines_intersect',
        'modules/color_converter',
        'modules/color_extraction',
        'modules/barcode',
        'modules/qrcode',
        'modules/ocr_simple',
        'modules/ocr_pretrain',
        'modules/ocv',
        'modules/measure_pair',
        'modules/find_peak',
        'modules/inspect_contour',
        'modules/brightness_adjust',
        'modules/crop_image',
        'modules/save_image',
        'modules/transform_image',
        'modules/polar_transform',
        'modules/warp_affine',
        'modules/point_to_point',
        'modules/point_to_line',
        'modules/coordinate_builder',
        'modules/if_else_logic',
        'modules/combine_logic',
        'modules/value_comparison',
        'modules/script_csharp',
        'modules/string_builder',
        'modules/number_calculator',
        'modules/variable',
        'modules/save_string_to_file',
        'modules/custom_overlay',
        'modules/tcp_ip',
        'modules/RS232_RS485',
        'modules/modbus_rtu',
      ],
    },
  ],
   
};

export default sidebars;
